### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by actcmsvn** [larvatecn/laravel-whois#1]
Hey,

Thanks for your Whois Query Extension, but how to use it?
Please detail.

Thanks,
De Zhong

**Comment by xutongle** [comment]
@actcmsvn 

composer require larva/laravel-whois -vv

    $info=  \Larva\Whois\Whois::lookup('baidu.com', true);
    $info=  \Larva\Whois\Whois::lookupRaw('google.com');
